server:
  port: 8080
keycloak:
  realm: tutorial
  auth-server-url: http://192.168.1.135:8080/auth
  ssl-required: external
  resource: spring
  credentials:
    secret: c28c2709-0971-4041-8272-7636a5fbc500
  use-resource-role-mappings: true
  bearer-only: true